#!/usr/bin/env python3
"""
VANTA CLI Wrapper for Project: 1c5a0ad2-0f18-4e8b-bd4c-88d28fff76c8
Auto-generated by VANTA Universal API Injector v3.0
"""

import sys
import requests
import json
import os

PROJECT_UUID = "1c5a0ad2-0f18-4e8b-bd4c-88d28fff76c8"
API_BASE = f"https://api.vanta.ai/v3/projects/{PROJECT_UUID}"
MASTER_KEY = os.getenv("VANTA_MASTER_API_KEY", "")

def execute_vanta_command(service_id: str, args: list):
    """Execute VANTA service command"""
    try:
        response = requests.post(
            f"{API_BASE}/services/{service_id}/execute",
            headers={"Authorization": f"Bearer {MASTER_KEY}"},
            json={"args": args, "project_uuid": PROJECT_UUID}
        )
        return response.json()
    except Exception as e:
        return {"error": str(e)}

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: vanta-cli.py <service_id> [args...]")
        sys.exit(1)
        
    service_id = sys.argv[1]
    args = sys.argv[2:]
    
    result = execute_vanta_command(service_id, args)
    print(json.dumps(result, indent=2))
